CREATE TABLE car
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand   VARCHAR(255)                            NOT NULL,
    model   VARCHAR(255)                            NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_car PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fist_name VARCHAR(255)                            NOT NULL,
    last_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE car
    ADD CONSTRAINT FK_CAR_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);